openapi: 3.2.0
info:
  title: ScyllaDB Cloud Account API
  version: 1.0.0
  description: '### Error codes mapping

    000001 Too many requests sent from your IP address.'
servers:
- url: /
security:
- Authorization: []
tags:
- name: Account
paths:
  /account/{accountId}/cloud-account:
    get:
      operationId: getCloudAccount
      description: Returns list of active cloud-accounts for all cloud-providers from given account
      summary: Get the list of active cloud-accounts
      x-public: true
      tags:
      - Account
      parameters:
      - in: header
        name: traceparent
        schema:
          type: string
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CloudAccount'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
  /account/{accountId}/cloud-account/{cloudAccountId}/region/{regionId}/zones:
    get:
      operationId: getCloudAccountZones
      description: Returns list of availability zones for a specific cloud account and region
      summary: Get availability zones for a cloud account and region
      x-public: true
      tags:
      - Account
      parameters:
      - in: header
        name: traceparent
        schema:
          type: string
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - description: CloudAccountId
        in: path
        name: cloudAccountId
        required: true
        schema:
          type: string
      - description: RegionId
        in: path
        name: regionId
        required: true
        schema:
          type: string
      - description: Instance Type ID to filter available zones
        in: query
        name: instanceTypeId
        required: false
        schema:
          type: string
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Unique identifier for the availability zone
                          example: use1-az2
                        name:
                          type: string
                          description: Name of the availability zone
                          example: us-east-1a
  /account/{accountId}/cluster/{clusterId}/notifications/email:
    post:
      operationId: setClusterNotificationEmail
      summary: Set cluster notification emails
      description: Set the contact email address(es) used for cluster notifications
      x-public: true
      tags:
      - Account
      parameters:
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - emails
              properties:
                emails:
                  items:
                    type: string
                  type: array
                  example:
                  - notifications@achme.com
                  - other@mail.com
      security:
      - Authorization: []
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/NotificationEmail'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: integer
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
  /account/default:
    get:
      operationId: getAccount
      description: Gives account details tied to authorized user.
      x-public: true
      summary: Gives account details tied to authorized user
      tags:
      - Account
      parameters:
      - in: header
        name: traceparent
        schema:
          type: string
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/Account'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
  /account/{accountId}/notifications/email:
    get:
      operationId: getNotificationsEmail
      summary: Get cluster notification emails
      description: Get the contact email address(es) used for cluster notifications
      x-public: true
      tags:
      - Account
      parameters:
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/NotificationEmail'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
    post:
      operationId: setNotificationEmail
      summary: Set cluster notification emails
      description: Set the contact email address(es) used for cluster notifications
      x-public: true
      tags:
      - Account
      parameters:
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - emails
              properties:
                emails:
                  items:
                    type: string
                  type: array
                  example:
                  - notifications@achme.com
                  - other@mail.com
      security:
      - Authorization: []
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/NotificationEmail'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: integer
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
components:
  schemas:
    NotificationEmail:
      x-public: true
      type: object
      properties:
        email:
          description: 'Deprecated: Emails should be used instead.'
          type: string
          deprecated: true
        emails:
          type: array
          items:
            type: string
        clusterNotifications:
          type: array
          items:
            $ref: '#/components/schemas/ClusterNotification'
    CloudAccountCheckStatus:
      x-public: true
      properties:
        boundaryPolicy:
          description: BoundaryPolicy is the status of the boundary policy in relation to the golden
          type: string
        cloudPolicy:
          description: CloudPolicy is the status of the cloud policy in relation to the golden
          type: string
        error:
          description: Error contains the last fatal error, if any
          type: string
        transientError:
          description: TransientError contains the last transient error, if any
          type: string
      type: object
    ClusterNotification:
      x-public: true
      type: object
      properties:
        clusterId:
          description: ID of the cluster
          type: integer
        clusterName:
          description: Name of the cluster
          type: string
        emails:
          type: array
          items:
            type: string
    CloudAccount:
      x-public: true
      properties:
        checkStatus:
          description: Holds the status of an AccountCloudCredential validation
          $ref: '#/components/schemas/CloudAccountCheckStatus'
        cloudProviderId:
          description: ID of the cloud provider (full list [get] /deployment/cloud-providers)
          type: integer
        id:
          description: Internal ID of the cloud account
          type: integer
        owner:
          description: Owner of the account [Scylla, Account]. Owner = Account means it's BYOA deployment.
          enum:
          - Scylla
          - Account
          type: string
        properties:
          $ref: '#/components/schemas/AWSCloudAccountProperties'
          description: AWS cloud account properties
        state:
          type: string
          description: Status of the cloud account
          enum:
          - NEW
          - ACTIVE
          - DELETED
      type: object
    Account:
      x-public: true
      properties:
        accountId:
          description: ID of the account
          type: integer
        accountStatus:
          description: Status of the account
          enum:
          - ACTIVE
          - INACTIVE
          - DELETED
          type: string
        role:
          description: Defines user role within the account
          enum:
          - ADMIN
          - MAINTAINER
          - VIEWER
          type: string
        userAccountStatus:
          description: User account status
          enum:
          - ACTIVE
          - INACTIVE
          - DELETED
          type: string
        name:
          description: Account name
          type: string
        userId:
          description: ID of the user
          type: integer
      type: object
    AWSCloudAccountProperties:
      x-public: true
      properties:
        awsAccountId:
          type: string
          description: AWS Account ID
        boundaryPolicyArn:
          type: string
          description: ARN of the boundary policy
        cloudPolicyArn:
          type: string
          description: ARN of the policy
        cloudRoleArn:
          type: string
          description: ARN of the role
        cloudRoleExternalId:
          type: string
          description: UUID generated by scylla-cloud (for internal reason)
      type: object
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: 'Authorization header, required in all authenticated requests.


        Header format: **Authorization: Bearer <token>**

        '
