openapi: 3.2.0
info:
  title: ScyllaDB Cloud Cluster Request API
  version: 1.0.0
  description: '### Error codes mapping

    000001 Too many requests sent from your IP address.'
servers:
- url: /
security:
- Authorization: []
tags:
- name: Cluster Request
paths:
  /account/{accountId}/cluster/{clusterId}/request:
    get:
      operationId: getClusterRequests
      description: Return the list of cluster requests created in the context of a given account.
      summary: Get the list of cluster requests created in context of given account
      x-public: true
      tags:
      - Cluster Request
      parameters:
      - in: header
        name: traceparent
        schema:
          type: string
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      - description: type of request
        in: query
        name: type
        schema:
          type: string
          enum:
          - ADD_DC
          - CREATE_CLUSTER
          - DELETE_CLUSTER
          - RESIZE_CLUSTER_V2
          - RESIZE_CLUSTER_V3
          - UPGRADE_CLUSTER
          - SCALE_CLUSTER
          - INSTALL_MANAGER
          - DNS
          - CREATE_VPC_PEERING
          - DELETE_VPC_PEERING
          - CREATE_CLUSTER_CONNECTION
          - DELETE_CLUSTER_CONNECTION
          - UPDATE_CLUSTER_CONNECTION
          - INSTALL_VECTOR_SEARCH
          - RESIZE_VECTOR_SEARCH
          - DELETE_VECTOR_SEARCH
      - description: status of request
        in: query
        name: status
        schema:
          type: string
          enum:
          - QUEUED
          - IN_PROGRESS
          - FAILED
          - COMPLETED
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ClusterRequest'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
  /account/{accountId}/cluster/request/{requestId}:
    get:
      operationId: getClusterRequestById
      description: Return details about a particular cluster request.
      summary: Get the details about cluster request
      x-public: true
      tags:
      - Cluster Request
      parameters:
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: header
        name: traceparent
        schema:
          type: string
      - description: RequestId
        in: path
        name: requestId
        required: true
        schema:
          type: integer
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/ClusterRequest'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
components:
  schemas:
    ClusterRequest:
      type: object
      x-public: true
      properties:
        accountId:
          type: integer
          description: ID of the account where cluster belongs to
        clusterId:
          type: integer
          description: ID of the cluster where the datacenter belongs to
        connectionID:
          type: integer
        id:
          type: integer
          description: ID of the cluster request
        progressDescription:
          type: string
          description: Request progress description
        progressPercent:
          type: integer
          description: Request processing progress
        requestBody:
          type: string
          description: JSON body of the request
        requestType:
          type: string
          description: Defines type of the request
          enum:
          - ADD_DC
          - CREATE_CLUSTER
          - DELETE_CLUSTER
          - RESIZE_CLUSTER_V2
          - RESIZE_CLUSTER_V3
          - UPGRADE_CLUSTER
          - SCALE_CLUSTER
          - INSTALL_MANAGER
          - DNS
          - CREATE_VPC_PEERING
          - DELETE_VPC_PEERING
          - CREATE_CLUSTER_CONNECTION
          - DELETE_CLUSTER_CONNECTION
          - UPDATE_CLUSTER_CONNECTION
          - INSTALL_VECTOR_SEARCH
          - RESIZE_VECTOR_SEARCH
          - DELETE_VECTOR_SEARCH
        status:
          type: string
          description: Status of the request
          enum:
          - QUEUED
          - IN_PROGRESS
          - FAILED
          - COMPLETED
          - CANCELLED
        ticketExternalID:
          description: External ID from Zendesk ticket
          type: string
        userFriendlyError:
          type: string
          description: Descriptive information about the potential error
          deprecated: true
        userId:
          type: integer
          description: ID of the user who created the request
        version:
          type: integer
          description: Version of the request. Always = 1
        provisioning:
          default: dedicated-vm
          enum:
          - dedicated-vm
          type: string
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: 'Authorization header, required in all authenticated requests.


        Header format: **Authorization: Bearer <token>**

        '
