openapi: 3.2.0
info:
  title: ScyllaDB Cloud Deployment API
  version: 1.0.0
  description: '### Error codes mapping

    000001 Too many requests sent from your IP address.'
servers:
- url: /
security:
- Authorization: []
tags:
- name: Deployment
paths:
  /deployment/cloud-providers:
    get:
      operationId: getCloudProviders
      summary: Get list of supported cloud providers
      description: Lists details about all cloud provider currently supported in Scylla-Cloud.
      x-public: true
      tags:
      - Deployment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: '040101'
                  data:
                    properties:
                      cloudProviders:
                        type: array
                        items:
                          $ref: '#/components/schemas/cloudProvider'
                    required:
                    - cloudProviders
  /deployment/scylla-versions:
    get:
      operationId: getScyllaVersions
      summary: Get all scylla cloud versions
      description: List all available ScyllaDB Cloud service versions.
      x-public: true
      tags:
      - Deployment
      parameters:
      - in: query
        description: Should include default values
        name: defaults
        required: false
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: '040101'
                  data:
                    properties:
                      defaultScyllaVersionId:
                        type: integer
                        example: 91
                      scyllaVersions:
                        type: array
                        items:
                          $ref: '#/components/schemas/scyllaVersion'
                    required:
                    - scyllaVersions
  /deployment/cloud-provider/{cloudProviderId}/regions:
    get:
      operationId: getCloudProviderRegions
      summary: Get all regions for the cloud provider
      description: Lists regions supported by the given cloud provider ID.
      x-public: true
      tags:
      - Deployment
      parameters:
      - in: path
        description: Cloud Provider ID (full list [get] /deployment/provider)
        name: cloudProviderId
        required: true
        schema:
          type: integer
          example: 1
      - in: query
        description: Should include default values
        name: defaults
        required: false
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorObject'
                - type: object
                  properties:
                    data:
                      properties:
                        regions:
                          type: array
                          items:
                            $ref: '#/components/schemas/region'
                        defaultRegionId:
                          type: integer
                          example: 30
                        defaultInstanceId:
                          type: integer
                          example: 40
                        instances:
                          type: array
                          items:
                            $ref: '#/components/schemas/instance'
                      required:
                      - regions
  /deployment/cloud-provider/{cloudProviderId}/region/{regionId}:
    get:
      operationId: getCloudProviderRegion
      summary: Get all instances for the selected region
      description: Lists instances supported in given region of given cloud provider.
      x-public: true
      tags:
      - Deployment
      parameters:
      - in: path
        description: Cloud Provider ID (full list [get] /deployment/provider)
        name: cloudProviderId
        required: true
        schema:
          type: integer
          example: 1
      - in: path
        description: Cloud Region ID (full list [get] /deployment/provider/{}/region)
        name: regionId
        required: true
        schema:
          type: integer
          example: 30
      - in: query
        description: Should include default values
        name: defaults
        required: false
        schema:
          type: boolean
          default: false
      - description: target for the requested instance types
        in: query
        name: target
        schema:
          type: string
          enum:
          - VECTOR_SEARCH
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: '040101'
                  data:
                    properties:
                      defaultInstanceId:
                        type: integer
                        example: 1
                      instances:
                        type: array
                        items:
                          $ref: '#/components/schemas/instance'
                    required:
                    - instances
components:
  schemas:
    errorObject:
      type: object
      x-public: true
      properties:
        error:
          type: string
          example: '040101'
    region:
      type: object
      description: Region and continent description
      x-public: true
      properties:
        id:
          type: integer
          description: ID of the region (internal for scylla-cloud)
          example: 30
        externalId:
          type: string
          description: External ID of the cloud provider region
          example: us-east1
        cloudProviderId:
          type: integer
          description: ID of the cloud provider (full list [get] /deployment/cloud-providers)
          example: 2
        name:
          type: string
          description: Name of the region
          example: us-east1
        dcName:
          type: string
          description: Name of the data center
          example: GCE_US_EAST_1
        fullName:
          type: string
          description: Full name of the region
          example: us-east1 (South Carolina)
        continent:
          type: string
          description: Continent name
        backupStorageGBCost:
          type: number
          description: Cost of storing 1 Gigabyte in backup
          example: 0.02
        trafficSameRegionInGBCost:
          type: number
          description: Cost of receiving 1 Gigabyte from the same region
          example: 0
        trafficSameRegionOutGBCost:
          type: number
          description: Cost of sending 1 Gigabyte to the same region
          example: 0
        trafficCrossRegionOutGBCost:
          type: number
          description: Cost of sending 1 Gigabyte to another region
          example: 0
        trafficInternetOutGBCost:
          type: number
          description: Cost of sending 1 Gigabyte to the internet
          example: 0
        multiRegionExternalId:
          description: External ID of the cloud provider multi-region
          example: us
          type: string
    instance:
      type: object
      description: Cloud provider instance pricing description
      x-public: true
      properties:
        id:
          type: integer
          description: ID of the instance type (internal for scylla-cloud)
          example: 40
        externalId:
          type: string
          description: External ID of the cloud provider instance type
          example: n2-highmem-2
        cloudProviderId:
          type: integer
          description: ID of the cloud provider (full list [get] /deployment/cloud-providers)
          example: 2
        groupDefault:
          type: boolean
          description: GroupDefault says which one is the default in a group of matching external_id
        displayOrder:
          type: integer
          description: Position when showing multiple instance types
          example: 3
        memory:
          type: integer
          description: Instance type RAM size in Megabytes
          example: 16384
        localDiskCount:
          type: integer
          description: Instance type disk count
          example: 1
        totalStorage:
          type: integer
          description: Instance type total storage size (uses base of 10 GB)
          example: 375
        cpuCount:
          type: integer
          description: Instance type CPU core count
          example: 2
        networkSpeed:
          type: integer
          description: Instance type network bandwidth in Megabytes per second
          example: 10
        networkSpeedDescription:
          description: Network performance description
          example: Maximum egress bandwidth, 10 Gbps
          type: string
        baseNetworkSpeed:
          description: The network performance in Megabytes per second
          example: 5
          type: integer
        externalStorageNetworkSpeed:
          type: integer
          description: Cloud provider storage bandwidth in Megabytes per second
          example: 0
        costPerHour:
          type: number
          description: Deprecated in favor of InstanceCostHourly
          deprecated: true
        environment:
          type: string
          description: Development clusters lack advanced features (e.g. Scylla Manager, monitoring alerts and many others) which are present in Production clusters
          enum:
          - PRODUCTION
          - DEVELOPMENT
        licenseCostOnDemandPerHour:
          type: number
          description: Deprecated in favor of SubscriptionCostHourly
          deprecated: true
        subscriptionCostHourly:
          type: number
          description: Scylla related part of the cost per hour
          example: 0.0956
        subscriptionCostHourlyXCloud:
          type: number
          description: Scylla related part of the cost per hour for XCloud
          example: 0.12
        subscriptionCostHourlyXCloudBYOA:
          type: number
          description: Scylla related part of the cost per hour for XCloud BYOA
          example: 0.15
        subscriptionCostMonthly:
          type: number
          description: Scylla related part of the cost per month
          example: 54
        subscriptionCostMonthlyXCloud:
          type: number
          description: Scylla related part of the cost per month for XCloud
          example: 65
        subscriptionCostYearly:
          type: number
          description: Scylla related part of the cost per year
          example: 560
        subscriptionCostYearlyXCloud:
          type: number
          description: Scylla related part of the cost per year for XCloud
          example: 650
        instanceCostHourly:
          type: number
          description: Cloud provider related part of the cost
          example: 0.03
        instanceFamily:
          description: Describes instance type best price-performance workloads
          example: n2
          type: string
        freeTier:
          description: This instance type can be used on a free tier cluster
          type: boolean
    scyllaVersion:
      type: object
      description: Represent version of the ScyllaDB installed on nodes
      x-public: true
      properties:
        id:
          type: integer
          description: ID of the service version
          example: 103
        version:
          type: string
          description: Name of the service version
          example: 2021.1.16
        description:
          type: string
          description: Version description
          example: Scylla Enterprise 2021.1.16
        newCluster:
          type: string
          description: Describes if this version should be available for creating new clusters using the frontend wizard
          example: DISABLED
          enum:
          - ENABLED
          - DISABLED
        serviceId:
          type: integer
          description: ID of the service
          example: 1
        name:
          type: string
          description: Version name
          example: Scylla Enterprise
    cloudProvider:
      type: object
      description: Cloud provider description
      x-public: true
      properties:
        id:
          type: integer
          description: ID of the cloud provider (internal for scylla-cloud)
          example: 1
        name:
          type: string
          description: Name of the cloud provider
          example: AWS
        rootAccountId:
          type: string
          description: Cloud provider account ID
          example: '123456789012'
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: 'Authorization header, required in all authenticated requests.


        Header format: **Authorization: Bearer <token>**

        '
