openapi: 3.2.0
info:
  title: ScyllaDB Cloud Account network cluster connection API
  version: 1.0.0
  description: '### Error codes mapping

    000001 Too many requests sent from your IP address.'
servers:
- url: /
security:
- Authorization: []
tags:
- name: Account network cluster connection
paths:
  /account/{accountId}/cluster/{clusterId}/network/vpc/connection:
    get:
      operationId: getConnections
      description: Lists details of all connection
      x-public: true
      parameters:
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      - description: List of connection types
        in: query
        name: type
        schema:
          type: string
      - description: Datacenter ID
        in: query
        name: dc
        schema:
          type: integer
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ClusterConnection'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
      summary: get the list of all connection
      tags:
      - Account network cluster connection
    post:
      operationId: createConnection
      description: Creates connection according to given request payload
      x-public: true
      parameters:
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      requestBody:
        description: Cluster connection request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cidrList:
                  description: CIDRList IPv4 networks to be accessible through this connection
                  items:
                    $ref: '#/components/schemas/CIDR'
                    type: array
                clusterDCID:
                  type: integer
                data:
                  type: object
                  properties:
                    ramARN:
                      description: AWS arn of the RAM
                      type: string
                      example: arn:aws:ram:us-east-1:123456789012:resource-share/12345678-1234-1234-1234-123456789012
                    tgwID:
                      description: ID of the TGW connection
                      type: string
                      example: tgw-12345678901234567
                name:
                  description: Name is the connection, only to show on UI
                  type: string
                type:
                  enum:
                  - AWS_TGW_ATTACHMENT
                  type: string
      security:
      - Authorization: []
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ClusterRequest'
                - type: object
                  properties:
                    connectionID:
                      type: integer
                      description: Connection ID that was created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
      summary: creates connection according to given request payload
      tags:
      - Account network cluster connection
  /account/{accountId}/cluster/{clusterId}/network/vpc/connection/{connectionId}:
    get:
      operationId: getConnection
      description: Get connection details
      x-public: true
      parameters:
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      - in: path
        description: Connection ID
        name: connectionId
        required: true
        schema:
          type: integer
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/ClusterConnection'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
      summary: get cluster connection details
      tags:
      - Account network cluster connection
    patch:
      operationId: updateConnection
      x-public: true
      parameters:
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      - in: path
        description: Connection ID
        name: connectionId
        required: true
        schema:
          type: integer
      requestBody:
        description: Cluster connection request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cidrList:
                  description: CIDRList IPv4 networks to be accessible through this connection
                  items:
                    $ref: '#/components/schemas/CIDR'
                  type: array
                name:
                  description: Name is the connection, only to show on UI
                  type: string
                status:
                  enum:
                  - ACTIVE
                  - INACTIVE
                  type: string
      security:
      - Authorization: []
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/ClusterConnection'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
      summary: Updates connection according to given request payload
      tags:
      - Account network cluster connection
    put:
      operationId: recreateConnection
      description: Recreates cloud objects related to connection according to given request payload. Updates ExternalID at the end
      x-public: true
      parameters:
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      - in: path
        description: Connection ID
        name: connectionId
        required: true
        schema:
          type: integer
      requestBody:
        description: Cluster connection request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cidrList:
                  description: CIDRList IPv4 networks to be accessible through this connection
                  items:
                    $ref: '#/components/schemas/CIDR'
                  type: array
                data:
                  type: object
                  properties:
                    ramARN:
                      description: AWS arn of the RAM
                      type: string
                      example: arn:aws:ram:us-east-1:123456789012:resource-share/12345678-1234-1234-1234-123456789012
                    tgwID:
                      description: ID of the TGW connection
                      type: string
                      example: tgw-12345678901234567
                name:
                  description: Name is the connection, only to show on UI
                  type: string
                status:
                  enum:
                  - ACTIVE
                  - INACTIVE
                  type: string
      security:
      - Authorization: []
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClusterRequest'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
      summary: Updates connection according to given request payload
      tags:
      - Account network cluster connection
    delete:
      description: Deletes the connection
      operationId: deleteConnection
      x-public: true
      parameters:
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      - in: path
        description: Connection ID
        name: connectionId
        required: true
        schema:
          type: integer
      security:
      - Authorization: []
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClusterRequest'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
      summary: deletes the connection
      tags:
      - Account network cluster connection
components:
  schemas:
    CIDR:
      type: string
      description: CIDR block in the form of ip/mask
      x-public: true
      example: 192.0.2.0/24
    ClusterConnectionAwaitingData:
      type: object
      x-public: true
      additionalProperties:
        type: string
    ClusterConnection:
      type: object
      description: Peering details information
      x-public: true
      properties:
        awaitingData:
          allOf:
          - type: object
          - $ref: '#/components/schemas/ClusterConnectionAwaitingData'
          description: AwaitingData represents information regarding the action that needs to be done to move connection creating process further
        awaitingForClient:
          type: boolean
          description: AwaitingForClient if true, then going to next stage require user action
        cidrlist:
          type: array
          description: CIDR list of the routes cluster have access through this connection
          items:
            $ref: '#/components/schemas/CIDR'
        clusterDCID:
          type: integer
          description: ID of the cluster DC
        clusterID:
          type: integer
          description: ID of the cluster
        clusterVPCID:
          type: integer
          description: ID of the VPC
        data:
          type: object
          additionalProperties:
            type: string
        externalID:
          type: string
          description: ExternalID and ID of the connection object on the cloud
        id:
          type: integer
          description: ID of the created connection (ScyllaDB internal)
        name:
          type: string
          description: Name if the connection, only to show on UI
        stage:
          type: string
          description: Stage if there is ongoing process it shows where this process exactly at
        stageMessage:
          type: string
          description: StageMessage is a message from stage processor why it can't move further
        status:
          type: string
          enum:
          - INIT
          - PENDING
          - ACTIVE
          - INACTIVE
          - DELETING
          - DELETED
          - FAILED
        type:
          type: string
          enum:
          - AWS_TGW_ATTACHMENT
    ClusterRequest:
      type: object
      x-public: true
      properties:
        accountId:
          type: integer
          description: ID of the account where cluster belongs to
        clusterId:
          type: integer
          description: ID of the cluster where the datacenter belongs to
        connectionID:
          type: integer
        id:
          type: integer
          description: ID of the cluster request
        progressDescription:
          type: string
          description: Request progress description
        progressPercent:
          type: integer
          description: Request processing progress
        requestBody:
          type: string
          description: JSON body of the request
        requestType:
          type: string
          description: Defines type of the request
          enum:
          - ADD_DC
          - CREATE_CLUSTER
          - DELETE_CLUSTER
          - RESIZE_CLUSTER_V2
          - RESIZE_CLUSTER_V3
          - UPGRADE_CLUSTER
          - SCALE_CLUSTER
          - INSTALL_MANAGER
          - DNS
          - CREATE_VPC_PEERING
          - DELETE_VPC_PEERING
          - CREATE_CLUSTER_CONNECTION
          - DELETE_CLUSTER_CONNECTION
          - UPDATE_CLUSTER_CONNECTION
          - INSTALL_VECTOR_SEARCH
          - RESIZE_VECTOR_SEARCH
          - DELETE_VECTOR_SEARCH
        status:
          type: string
          description: Status of the request
          enum:
          - QUEUED
          - IN_PROGRESS
          - FAILED
          - COMPLETED
          - CANCELLED
        ticketExternalID:
          description: External ID from Zendesk ticket
          type: string
        userFriendlyError:
          type: string
          description: Descriptive information about the potential error
          deprecated: true
        userId:
          type: integer
          description: ID of the user who created the request
        version:
          type: integer
          description: Version of the request. Always = 1
        provisioning:
          default: dedicated-vm
          enum:
          - dedicated-vm
          type: string
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: 'Authorization header, required in all authenticated requests.


        Header format: **Authorization: Bearer <token>**

        '
