openapi: 3.2.0
info:
  title: ScyllaDB Cloud Account Cluster Network API
  version: 1.0.0
  description: '### Error codes mapping

    000001 Too many requests sent from your IP address.'
servers:
- url: /
security:
- Authorization: []
tags:
- name: Account Cluster Network
paths:
  /account/{accountId}/cluster/{clusterId}/network/firewall/allowed:
    post:
      operationId: createFirewallAllowedRule
      summary: Create a new firewall allowed rule
      description: Create a new firewall allowed rule.
      x-public: true
      parameters:
      - in: header
        name: traceparent
        schema:
          type: string
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      requestBody:
        description: ipAddress and CIDR block
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ipAddress:
                  type: string
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/FirewallRules'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
      tags:
      - Account Cluster Network
    get:
      operationId: getFirewallAllowedRules
      summary: Get the cluster firewall rules
      description: List the cluster firewall rules.
      x-public: true
      parameters:
      - in: header
        name: traceparent
        schema:
          type: string
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/FirewallRules'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
      tags:
      - Account Cluster Network
  /account/{accountId}/cluster/{clusterId}/network/firewall/allowed/{ruleId}:
    delete:
      operationId: deleteFirewallAllowedRule
      summary: Delete the firewall rule of given id
      description: Delete the firewall rule of a given id.
      x-public: true
      parameters:
      - in: header
        name: traceparent
        schema:
          type: string
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      - description: Rule ID
        in: path
        name: ruleId
        required: true
        schema:
          type: integer
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/FirewallRules'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
      tags:
      - Account Cluster Network
  /account/{accountId}/cluster/{clusterId}/network/vpc/peer:
    get:
      operationId: getVPCPeeringList
      summary: Get the details of all cluster VPC peers
      description: List the details of all cluster VPC peers.
      x-public: true
      tags:
      - Account Cluster Network
      parameters:
      - in: header
        name: traceparent
        schema:
          type: string
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ClusterVPCPeeringInfo'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
    post:
      operationId: createVPCPeering
      summary: Create VPC peering according to given request payload
      description: Create VPC peering according to a given request payload.
      x-public: true
      tags:
      - Account Cluster Network
      parameters:
      - in: header
        name: traceparent
        schema:
          type: string
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      - in: query
        description: Run the request in an asynchronous mode
        name: async
        required: false
        schema:
          type: boolean
      requestBody:
        description: Peering details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cidrBlock:
                  type: string
                  description: Single address or list of comma separated CIDR block addresses,
                  example: 10.10.0.0/16
                dcId:
                  type: integer
                vpcId:
                  type: string
                ownerId:
                  type: string
                regionId:
                  description: Applicable to AWS only,
                  type: integer
                allowCql:
                  type: boolean
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: object
                    properties:
                      externalId:
                        type: string
                      id:
                        type: integer
                      requestId:
                        type: integer
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
  /account/{accountId}/cluster/{clusterId}/network/vpc/peer/{peerId}:
    get:
      operationId: getVPCPeeringInfo
      summary: Get the details of VPC peer
      description: List the details of cluster VPC peer.
      x-public: true
      tags:
      - Account Cluster Network
      parameters:
      - in: header
        name: traceparent
        schema:
          type: string
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      - in: path
        description: Peer ID
        name: peerId
        required: true
        schema:
          type: integer
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/ClusterVPCPeeringInfo'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
    put:
      operationId: updateVPCPeering
      summary: Updates VPC peering according to given request payload
      description: Updates VPC peering according to given request payload.
      x-public: true
      tags:
      - Account Cluster Network
      parameters:
      - in: header
        name: traceparent
        schema:
          type: string
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      - in: path
        description: Peer ID
        name: peerId
        required: true
        schema:
          type: integer
      requestBody:
        description: Peering details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: Can be "ACTIVE" or "INACTIVE", triggers peering to switch to desired state
                  example: ACTIVE
                cidrBlock:
                  type: string
                  description: Single address or list of comma separated CIDR block addresses,
                  example: 10.10.0.0/16
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClusterVPCPeeringInfo'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
    delete:
      operationId: deleteVPCPeering
      summary: Schedule delete VPC peering request (async)
      description: Schedule delete VPC peering request (async). Returns a cluster request
      x-public: true
      tags:
      - Account Cluster Network
      parameters:
      - in: header
        name: traceparent
        schema:
          type: string
      - in: path
        description: Account ID
        name: accountId
        required: true
        schema:
          type: integer
      - in: path
        description: Cluster ID
        name: clusterId
        required: true
        schema:
          type: integer
      - in: path
        description: Peer ID
        name: peerId
        required: true
        schema:
          type: integer
      security:
      - Authorization: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    $ref: '#/components/schemas/ClusterRequest'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: integer
        '500':
          description: Internal Server Error
components:
  schemas:
    CIDR:
      type: string
      description: CIDR block in the form of ip/mask
      x-public: true
      example: 192.0.2.0/24
    ClusterRequest:
      type: object
      x-public: true
      properties:
        accountId:
          type: integer
          description: ID of the account where cluster belongs to
        clusterId:
          type: integer
          description: ID of the cluster where the datacenter belongs to
        connectionID:
          type: integer
        id:
          type: integer
          description: ID of the cluster request
        progressDescription:
          type: string
          description: Request progress description
        progressPercent:
          type: integer
          description: Request processing progress
        requestBody:
          type: string
          description: JSON body of the request
        requestType:
          type: string
          description: Defines type of the request
          enum:
          - ADD_DC
          - CREATE_CLUSTER
          - DELETE_CLUSTER
          - RESIZE_CLUSTER_V2
          - RESIZE_CLUSTER_V3
          - UPGRADE_CLUSTER
          - SCALE_CLUSTER
          - INSTALL_MANAGER
          - DNS
          - CREATE_VPC_PEERING
          - DELETE_VPC_PEERING
          - CREATE_CLUSTER_CONNECTION
          - DELETE_CLUSTER_CONNECTION
          - UPDATE_CLUSTER_CONNECTION
          - INSTALL_VECTOR_SEARCH
          - RESIZE_VECTOR_SEARCH
          - DELETE_VECTOR_SEARCH
        status:
          type: string
          description: Status of the request
          enum:
          - QUEUED
          - IN_PROGRESS
          - FAILED
          - COMPLETED
          - CANCELLED
        ticketExternalID:
          description: External ID from Zendesk ticket
          type: string
        userFriendlyError:
          type: string
          description: Descriptive information about the potential error
          deprecated: true
        userId:
          type: integer
          description: ID of the user who created the request
        version:
          type: integer
          description: Version of the request. Always = 1
        provisioning:
          default: dedicated-vm
          enum:
          - dedicated-vm
          type: string
    ClusterVPCPeeringInfo:
      type: object
      x-public: true
      properties:
        externalId:
          type: string
          description: External ID of the VPC peering
          example: pcx-21f1c5d76e55f2b0c
        id:
          type: integer
          description: ID of the VPC peering (scyllaDB internal)
        networkName:
          type: string
          description: Name of the network (GCP specific)
        ownerId:
          type: string
          description: Owner of the peering (AWS account ID or GCP project ID)
        vpcId:
          type: string
          description: Peer VPC external ID
          example: vpc-11f1c5d76e55f2b0c
        cidrList:
          description: List of CIDRs
          items:
            $ref: '#/components/schemas/CIDR'
          type: array
        cidrBlockVerified:
          type: array
          description: List of CIDRs
          items:
            $ref: '#/components/schemas/CIDR'
        regionId:
          type: integer
          description: ID of the cloud provider region, returned for AWS clusters only (full list [get] /deployment/cloud-provider/{}/regions)
        projectId:
          type: string
          description: GCP Project ID (GCP specific)
        status:
          type: string
          description: Status of the VPC peering
          enum:
          - INITIATING_REQUEST
          - PENDING_ACCEPTANCE
          - DELETING
          - DELETED
          - FAILED
          - REJECTED
          - EXPIRED
          - PROVISIONING
          - ACTIVE
          - MISMATCHED
          - INACTIVE
        expiresAt:
          type: string
          description: Expiration time
        allowCql:
          type: boolean
          description: Is CQL connection allowed for peering CIDRs
        dcId:
          description: ID of the cluster's data center
          type: integer
    FirewallRules:
      type: object
      description: List of CIDR formatted rules a.b.c.d/e
      x-public: true
      properties:
        clusterId:
          type: integer
          description: ID of the cluster where the datacenter belongs to
        id:
          type: integer
          description: ID of the firewall allowed rule
        address:
          $ref: '#/components/schemas/CIDR'
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: 'Authorization header, required in all authenticated requests.


        Header format: **Authorization: Bearer <token>**

        '
